"""Nickname mappings for common English names."""

from __future__ import annotations

NICKNAME_MAP: dict[str, set[str]] = {
    'abigail': {'abby', 'gail'},
    'abraham': {'abe', 'bram'},
    'albert': {'al', 'bert', 'alberto'},
    'alexander': {'al', 'alec', 'alex', 'sacha', 'sandy', 'sasha', 'xander', 'zander'},
    'alexandra': {'alex', 'ally', 'lex', 'lexi', 'sandra', 'sandy', 'sasha', 'sondra'},
    'alfred': {'alf', 'alfie', 'fred'},
    'alvin': {'al'},
    'amanda': {'amy', 'mandy'},
    'amelia': {'amy', 'mia', 'millie'},
    'andrew': {'andrei', 'andr\u00e9s', 'andy', 'drew'},
    'ann': {'annie', 'nancy'},
    'anthony': {'antoine', 'anton', 'antonio', 'tony'},
    'arnold': {'arnie'},
    'arthur': {'art', 'artie'},
    'augustus': {'augie', 'gus'},
    'barbara': {'babs', 'barb', 'barbie', 'basia'},
    'benjamin': {'ben', 'benji', 'benny', 'beno\u00eet', 'jamie'},
    'bernadette': {'bernie', 'nadia'},
    'caroline': {'caro', 'carol', 'carrie', 'caz'},
    'catherine': {'cat', 'cathy', 'kate', 'katie', 'kit', 'kitty', 'rina'},
    'charles': {'carl', 'carlos', 'charlie', 'chaz', 'chip', 'chuck'},
    'charlotte': {'carla', 'charlie', 'lola', 'lottie'},
    'christina': {'chris', 'chrissy', 'tina', 'xtina'},
    'christopher': {'chris', 'kit', 'topher'},
    'cynthia': {'cindy', 'cyn'},
    'daniel': {'dan', 'dani', 'danilo', 'danny'},
    'david': {'dai', 'dave', 'davy', 'dawid'},
    'deborah': {'deb', 'debbie', 'debora', 'debra'},
    'dennis': {'den', 'denny'},
    'dominic': {'dom', 'nick'},
    'dorothy': {'dolly', 'dorota', 'dot', 'dottie', 'dotty'},
    'douglas': {'doug', 'dougie'},
    'edward': {'ed', 'eddie', 'eduardo', 'ned', 'ted', 'teddy'},
    'eleanor': {'el', 'ella', 'ellie', 'lea', 'lenka', 'nell', 'nellie', 'nora'},
    'elizabeth': {'bess', 'beth', 'betsy', 'betty', 'elisa', 'elisabeth', 'ella', 'elle', 'elsie', 'elsa', 'isabel', 'isabella', 'libby', 'lisa', 'liz', 'lizbet', 'liza', 'lizzie'},
    'frances': {'fran', 'franca', 'frankie', 'franny'},
    'francis': {'fran', 'frank', 'frankie'},
    'francisco': {'cisco', 'paco', 'pancho'},
    'franklin': {'franc', 'franco', 'frank', 'frankie'},
    'frederick': {'fernando', 'fred', 'freddy', 'friedrich', 'fritz', 'rick'},
    'gabriel': {'gabe', 'gabby'},
    'gabrielle': {'ella', 'gabby'},
    'george': {'geordie', 'jorge'},
    'geraldine': {'dina', 'geri', 'gerry'},
    'gregory': {'greg'},
    'harold': {'hal', 'harry'},
    'helen': {'ela', 'ilona', 'lena', 'nell', 'nellie'},
    'henry': {'enrique', 'hal', 'hank', 'harry'},
    'ignatius': {'iggy', 'nacio'},
    'isidore': {'izzy'},
    'jacob': {'coby', 'jake', 'jakub', 'jay', 'yakov'},
    'jacqueline': {'jackie', 'jacqui'},
    'james': {'diego', 'jago', 'jaime', 'jamie', 'jim', 'jimmy'},
    'janet': {'jan', 'nettie', 'zhanna'},
    'jeffrey': {'geoff', 'jeff'},
    'jennifer': {'jen', 'jenna', 'jenni', 'jenny'},
    'jeremiah': {'jeremy', 'jerry'},
    'jeremy': {'jerry'},
    'joan': {'jo', 'joanna', 'joanie'},
    'joanna': {'jo', 'joanie'},
    'john': {'jack', 'jan', 'johann', 'johnny', 'jon', 'juan', 'ivan', 'sean', 'shane', 'jock'},
    'jonathan': {'jono', 'jon', 'johnny', 'nate', 'yonatan'},
    'joseph': {'giuseppe', 'joe', 'joey', 'jose', 'pepe', 'youssef'},
    'judith': {'jude', 'judy'},
    'julian': {'jules'},
    'karen': {'kari', 'karina', 'kay'},
    'katherine': {'cathy', 'kat', 'katarina', 'katharina', 'kate', 'katie', 'kathy', 'kit', 'kitty', 'rina'},
    'kenneth': {'ken', 'kenny'},
    'kimberly': {'kim', 'kimmy'},
    'lauren': {'laurie', 'lorena', 'ren'},
    'lawrence': {'larry', 'laurie', 'lorenzo', 'lorne'},
    'leonard': {'len', 'lenny', 'leo', 'leonardo'},
    'linda': {'lin', 'lindy'},
    'louis': {'lou', 'louie'},
    'louise': {'lou', 'louie', 'luisa'},
    'margaret': {'daisy', 'greta', 'gretchen', 'madge', 'maggie', 'maisie', 'marge', 'margie', 'meg', 'peggy', 'rita'},
    'marilyn': {'lyn', 'mari', 'mary'},
    'matthew': {'mat\u00edas', 'matt', 'matteo', 'matty', 'mateusz'},
    'melissa': {'lisa', 'mel', 'melis', 'missy'},
    'michael': {'mick', 'micky', 'mike', 'mikey', 'misha'},
    'michelle': {'elle', 'mish', 'shelly'},
    'nancy': {'ana', 'nan', 'nanci', 'nannie'},
    'nathaniel': {'nat', 'nate', 'nathan'},
    'nicholas': {'cole', 'klaus', 'nick', 'nicky', 'nicol\u00e1s', 'niko', 'nikola'},
    'nicole': {'cole', 'nicki', 'nicky'},
    'oliver': {'ollie'},
    'olivia': {'liv', 'livvy', 'ollie'},
    'pamela': {'pam'},
    'patricia': {'pat', 'patti', 'patty', 'patsy', 'patrizia', 'trish', 'tricia'},
    'patrick': {'paddy', 'pat', 'rick'},
    'penelope': {'nell', 'penny'},
    'peter': {'pedro', 'pete', 'petya', 'pierre'},
    'philip': {'felipe', 'phil', 'pip'},
    'priscilla': {'cilla', 'prissy'},
    'ralph': {'ralphie'},
    'raymond': {'ram\u00f3n', 'ray'},
    'rebecca': {'becca', 'becks', 'becky', 'beka', 'rebekah'},
    'reginald': {'reg', 'reggie'},
    'richard': {'dick', 'dicky', 'ricardo', 'rich', 'rick', 'ricky'},
    'robert': {'bert', 'bob', 'bobby', 'rob', 'robbie', 'roberto', 'rupert'},
    'ronald': {'ron', 'ronnie'},
    'samantha': {'mantha', 'sam', 'sammy'},
    'samuel': {'sam', 'sami', 'sammy'},
    'sandra': {'aleksandra', 'sandi', 'sandy'},
    'sebastian': {'bash', 'bastian', 'seb'},
    'shirley': {'shirl'},
    'sophia': {'soph', 'sophie'},
    'stephanie': {'steph', 'stephie', 'stevie'},
    'steven': {'esteban', 'steve', 'stevie', 'steph'},
    'stephen': {'esteban', 'steph', 'steve', 'stevie'},
    'susan': {'sue', 'suki', 'susana', 'susie', 'suzy', 'zuzana'},
    'terence': {'terry', 'tez'},
    'theresa': {'teresa', 'terri', 'terry', 'tess', 'tessa', 'tracy'},
    'theodore': {'ted', 'teddy', 'teo', 'theo'},
    'thomas': {'tom', 'tom\u00e1s', 'tommy'},
    'timothy': {'tim', 'timmy', 'timo'},
    'valerie': {'val', 'valeria'},
    'vanessa': {'nessa', 'van'},
    'veronica': {'ronna', 'ronnie', 'vera'},
    'victoria': {'tori', 'vic', 'vicki', 'vicky', 'vika'},
    'vincent': {'vince', 'vinnie', 'vinny'},
    'virginia': {'ginger', 'ginny', 'nia', 'virgie'},
    'walter': {'walt', 'wally'},
    'william': {'bill', 'billy', 'guillaume', 'liam', 'will', 'willy'},
    'yvette': {'eve', 'iveta', 'yvie'},
    'zachary': {'zach', 'zack'},
}
